### ISSUE TITLE
Error: Cannot find module 'multicodec/src/name-table'

### ISSUE THREAD

**Issue by carsonfarmer** [ipld/js-get-codec#4]
Because this library digs into multicodec for the `name-table`, a recent change in multicodec (0.5.6 -> 0.5.7) which removed this module is causing issues with `get-codec` (and the packages that depend on it). This import should be updated to reflect the new structure and the version bumped or updated to match expectations.

**Comment by rvagg** [comment]
the most amusing thing about this is the cause of the removal and person that did it https://github.com/multiformats/js-multicodec/commit/f3766e54c2f91616034a5be4d7c4739bca876ab2
tee hee hee

**Comment by rvagg** [comment]
https://github.com/ipld/js-get-codec/pull/5

**Comment by carsonfarmer** [comment]
Nice, thanks for the quick fix!
